name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:v0.26.4
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Install Ruby
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: project

      - name: Initialize
        working-directory: project
        run: |
          west init -l .
          west update

      - name: Build firmware
        working-directory: project/asset_tracker_v2
        run: |
          west build -b thingy91_nrf9160_ns

      - name: Twister Tests
        working-directory: project/asset_tracker_v2
        run: |
          ../../zephyr/scripts/twister -G  --testsuite-root ./tests/

      - name: Archive test result
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: twister
          path: project/asset_tracker_v2/twister-out

      - name: Archive firmware
        if: success() || failure()
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: |
            project/asset_tracker_v2/build/zephyr/zephyr.elf
            project/asset_tracker_v2/build/zephyr/merged.hex
            project/asset_tracker_v2/build/zephyr/app_update.bin
            project/asset_tracker_v2/build/zephyr/app_signed.hex
            project/asset_tracker_v2/build/zephyr/zephyr.dts
            project/asset_tracker_v2/build/zephyr/.config

