name: Publish firmware bundles to nRF Cloud

on:
  workflow_dispatch:

jobs:
  publish:
    environment: production

    name: Publish firmware bundles to nRF Cloud

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Keep npm cache around to speed up installs
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: build-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci --no-audit

      - run: node register-firmware-bundles.js
        env:
          NRF_CLOUD_API_KEY: ${{ secrets.NRF_CLOUD_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
